### ISSUE TITLE
india timezone

### ISSUE THREAD

**Issue by hiteshinde** [kilgoretrout1985/django_infopush#1]
Hey, if i want to push notification at 11 am IST, what time I should put in admin

**Comment by kilgoretrout1985** [comment]
Hello, 
if you set 11:00:00 in admin, each of your subscribers will receive this push approximately at 11 am **in it's local timezone.** 

Subscribers, registered at IST timezone, will receive this at 11 am IST. 
UTC-subscribers will receive at 11 am UTC and so forth...
