### ISSUE TITLE
Drop Python 2 compatibilty

### ISSUE THREAD

**Issue by don-mums** [kilgoretrout1985/django_infopush#2]
Django 1.11 will soon not be supported. Exactly end of April 2020. This is the last version to support Python 2.7. Support for Python 2.7 will end in [little more than a month](https://pythonclock.org/). 

Currently it does not make much sense to write the code in a way that will support both Python 2 and Python 3. I'm writing here mainly because you don't state versions of Python that you plan to support nor versions of Django. But from the code itself I can see that you use decorators that enable both versions to work. I consider those redundant for the future and worth removing from this project.

**Comment by kilgoretrout1985** [comment]
Hello, 

currently I'm not actively working on this package, but I've planned to support Python and Django versions according to https://www.djangoproject.com/download/#supported-versions 

Supported versions are not clearly stated, but you can find actual versions in [tox.ini](https://github.com/kilgoretrout1985/django_infopush/blob/master/tox.ini)

And I think April 2020 is a great time to stop Python 2 support in django-push without harming any users if there is any ))
