### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by ghost** [kilgoretrout1985/django_infopush#5]
Please, keep only one instance of documentation if you fail to maintain several ones.

I opened an issue recently. About the documentation.
Ok. You fixed it. But what about https://pypi.org/project/django-infopush/?

Maybe you'd better not to keep it at all? One doc at github is enough.

**Comment by kilgoretrout1985** [comment]
Docs on pypi will be automatically updated from github's README.rst with the new release.

**Comment by ghost** [comment]
Thank you.
